services:
  inventory_db:
    image: postgres:15-alpine
    container_name: inventory_db
    restart: always
    environment:
      POSTGRES_USER: $USER_DB
      POSTGRES_PASSWORD: $PASSWORD_DB
      POSTGRES_DB: movies_db
    ports:
      - "5432:5432"
    volumes:
      - inventory_data:/var/lib/postgresql/data
  billing_db:
    image: postgres:15-alpine
    container_name: billing_db
    restart: always
    environment:
      POSTGRES_USER: $USER_DB
      POSTGRES_PASSWORD: $PASSWORD_DB
      POSTGRES_DB: billing_db
    ports:
      - "5433:5432"
    volumes:
      - billing_data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/data
volumes:
  inventory_data:
  billing_data:
  rabbitmq_data:
